### ISSUE TITLE
Mari's Shop: New items added

### ISSUE THREAD

**Issue by Zalmez** [datmeal/lostarkchecklist#35]
Today I saw that Mari's shop now has:

- Honor Shard Pouch (L) [20] (291 blue crystals)
- Tailoring: Applied Mending (Bound) [4] (Legendary) (260 Blue crystals)

Awesome if these could be added to the list
image attached:
![image](https://user-images.githubusercontent.com/8438702/178035809-a6ff690e-cf87-4813-b19b-fc387f770c4d.png)

**Comment by datmeal** [comment]
@Zalmez 
Somehow I missed this ticket!
I will add today
