### ISSUE TITLE
Advanced Character Customization

### ISSUE THREAD

**Issue by datmeal** [datmeal/lostarkchecklist#9]
Names of each character should be clickable to expand a menu/dialog to fill in extra information, like item level, avatar image(?), rest bonus, assign Una's Task, and set current Una-related rep/maximum rep required.

**All of this is optional, and hidden when not setup!**

A modal would be easiest to implement without disturbing the table layout. Would need to make it clear that the character name can be clicked to open a modal somehow.

Rest Bonus:
Since automatic daily reset requires overhauling the current Event Timer component to a higher place to interact with the Checklist component, Rest Bonus should be manually configurable at any time, as well as reacting to the Reset Dailies button.
- The advanced character menu should have an input box to enter the current rest bonus of the character. Should be easy.
- When Reset Dailies is clicked, one of two things happen:
  - If there are 0 checkboxes for chaos dungeons, add 20 to Rest Bonus.
  - If there are x checkboxes for chaos dungeons, add 10 * x to Rest Bonus.
- Also when a checkbox is clicked for chaos/guardians, if rest bonus >= 20, subtract 20 Rest Bonus.

Una's Task:
Not a permanent solution, but a temporary improvement to Una's Tasks:
- Inside the advanced character window, there will be three autocomplete boxes to fill in Una's tasks, with two input boxes next to it, Current Rep / Maximum Required Rep.
- When a checkbox is clicked, 10 rep is added to current rep.
- When rep numbers are added to character window, some kind of progress bar is shown.
  - not sure how visible this will be. could be a real bar in its own row or maybe just a background color?
- What about Una's rest bonus?

**Comment by vazh** [comment]
> A modal would be easiest to implement without disturbing the table layout. Would need to make it clear that the character name can be clicked to open a modal somehow.

just give them some button to click, and then make it so that the name open the same modal.

**Comment by datmeal** [comment]
Progress:
![tooki_advancedchar_WIP](https://user-images.githubusercontent.com/7368593/160708542-60d05fe7-7a41-410f-b028-fc959bd30f3d.jpg)

Probably need to clean up the modal a bit but it works for the most part.

**Comment by datmeal** [comment]
Released! Closing.
